

# USAGES
TYPE_PLANE = "Plane"
TYPE_TRAIN = "Train"
TYPE_COACH = "Coach"   # Inter cities
TYPE_BUS = "Bus"       # Inner agglomeration
TYPE_METRO = "Metro"
TYPE_WAIT = "Waiting"
TYPE_AUTOMOBILE = "Automobile"
TYPE_METRO = "Metro"
TYPE_BIKE = "Bike"
TYPE_WALK = "Walking"
TYPE_TRANSFER = "Transfer"
TYPE_TRAM = "Tram"

# UNITES
UNIT_CONVERSION = 1

# WAITING_PERIODS
WAITING_PERIOD_TRAINLINE = 15 * 60
WAITING_PERIOD_AIRPORT = 120 * 60
WAITING_PERIOD_OUIBUS = 15 * 60
